# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Logger_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Logger_iOS

  target 'Logger_iOSTests' do
    # Pods for testing
  end

end
